import { Resend } from 'resend';

/**
 * Sends an urgent notification email to management about a pending XL/XXL job.
 * @param {object} params
 * @param {string} params.clientName
 * @param {string} params.jobId
 * @param {string} params.deliverable
 * @param {string} params.priority
 * @param {string} params.dueDate
 * @param {number} params.daysRemaining
 * @returns {Promise<boolean>}
 */
export async function sendAlertEmail({ clientName, jobId, deliverable, priority, dueDate, daysRemaining, isPanasonic }) {
  const isPanasonicCheck = isPanasonic || (clientName || '').toLowerCase().includes('panasonic');
  const resendApiKey = process.env.RESEND_API_KEY;
  const managementEmail = process.env.MANAGEMENT_EMAIL;
  const fromEmail = process.env.SMTP_FROM || 'Account Health Alerts <onboarding@resend.dev>';

  if (!resendApiKey) {
    console.warn('[emailService] RESEND_API_KEY not set. Skipping email delivery.');
    return false;
  }
  if (!managementEmail) {
    console.warn('[emailService] MANAGEMENT_EMAIL not set. Skipping email delivery.');
    return false;
  }

  const resend = new Resend(resendApiKey);

  const subject = `[Urgent Alert] ${priority} Job Due in ${daysRemaining} Days for ${clientName}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #f8fafc;">
      <h2 style="color: #d97706; margin-top: 0; font-size: 20px;">⚠️ High-Priority Job Due Soon</h2>
      <p style="font-size: 15px; color: #334155; line-height: 1.5; margin-bottom: 20px;">
        The following high-priority <strong>${priority}</strong> job is scheduled for delivery in <strong>${daysRemaining} days</strong>.
      </p>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; width: 140px; border-bottom: 1px solid #f1f5f9;">Client:</td>
          <td style="padding: 8px 0; color: #0f172a; font-weight: 500; border-bottom: 1px solid #f1f5f9;">${clientName}</td>
        </tr>
        ${isPanasonicCheck ? '' : `
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Job ID:</td>
          <td style="padding: 8px 0; color: #0f172a; font-family: monospace; font-size: 13px; border-bottom: 1px solid #f1f5f9;">${jobId}</td>
        </tr>
        `}
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Deliverable:</td>
          <td style="padding: 8px 0; color: #0f172a; font-weight: 500; border-bottom: 1px solid #f1f5f9;">${deliverable}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Priority / Size:</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f1f5f9;">
            <span style="background-color: ${priority === 'XXL' ? '#0d9488' : '#d97706'}; color: white; padding: 3px 10px; border-radius: 6px; font-weight: bold; font-size: 11px; letter-spacing: 0.05em;">
              ${priority}
            </span>
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Due Date:</td>
          <td style="padding: 8px 0; color: #ef4444; font-weight: bold; border-bottom: 1px solid #f1f5f9;">${dueDate}</td>
        </tr>
      </table>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
      <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">
        This is an automated alert generated by the Account Health Tracker Dashboard.
      </p>
    </div>
  `;

  try {
    const { error } = await resend.emails.send({
      from: fromEmail,
      to: managementEmail,
      subject,
      html,
    });
    if (error) {
      console.error(`[emailService] Resend API error for Job ${jobId}:`, error.message);
      return false;
    }
    console.log(`[emailService] Alert email sent for Job ${jobId} to ${managementEmail}.`);
    return true;
  } catch (err) {
    console.error(`[emailService] Failed to send alert email for Job ${jobId}:`, err.message);
    return false;
  }
}

/**
 * Sends a single summary email for all pending high-priority jobs of a client.
 * @param {object} params
 * @param {string} params.clientName
 * @param {Array} params.jobs
 * @returns {Promise<boolean>}
 */
export async function sendClientSummaryEmail({ clientName, jobs }) {
  const resendApiKey = process.env.RESEND_API_KEY;
  const managementEmail = process.env.MANAGEMENT_EMAIL;
  const fromEmail = process.env.SMTP_FROM || 'Account Health Alerts <onboarding@resend.dev>';

  if (!resendApiKey) {
    console.warn('[emailService] RESEND_API_KEY not set. Skipping email delivery.');
    return false;
  }
  if (!managementEmail) {
    console.warn('[emailService] MANAGEMENT_EMAIL not set. Skipping email delivery.');
    return false;
  }

  const resend = new Resend(resendApiKey);

  const count = jobs.length;
  const subject = `[Urgent Alert] ${count} High-Priority Job${count !== 1 ? 's' : ''} Pending for ${clientName}`;
  const isPanasonicCheck = (clientName || '').toLowerCase().includes('panasonic') || jobs.some(j => j.isPanasonic);

  const jobsRowsHtml = jobs.map(job => `
    <tr>
      ${isPanasonicCheck ? '' : `<td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-family: monospace; font-size: 13px; color: #475569;">${job.jobId}</td>`}
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #0f172a;">${job.deliverable}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; text-align: center;">
        <span style="background-color: ${job.priority === 'XXL' ? '#0d9488' : '#d97706'}; color: white; padding: 3px 8px; border-radius: 4px; font-weight: bold; font-size: 11px;">
          ${job.priority}
        </span>
      </td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #ef4444; font-weight: 600;">${job.dueDate}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #475569; font-weight: 500;">
        ${job.daysRemaining <= 0 ? 'Overdue' : `${job.daysRemaining} days`}
      </td>
    </tr>
  `).join('');

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #f8fafc;">
      <h2 style="color: #d97706; margin-top: 0; font-size: 20px;">⚠️ High-Priority Jobs Alert</h2>
      <p style="font-size: 15px; color: #334155; line-height: 1.5; margin-bottom: 15px;">
        There are <strong>${count}</strong> pending high-priority (XL/XXL) jobs for <strong>${clientName}</strong> that are due today or overdue.
      </p>
      <div style="overflow-x: auto; margin-top: 15px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px; background: white; border: 1px solid #e2e8f0; border-radius: 8px;">
          <thead>
            <tr style="background-color: #f1f5f9; text-align: left;">
              ${isPanasonicCheck ? '' : `<th style="padding: 10px; color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;">Job ID</th>`}
              <th style="padding: 10px; color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;">Deliverable</th>
              <th style="padding: 10px; color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;">Priority</th>
              <th style="padding: 10px; color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;">Due Date</th>
              <th style="padding: 10px; color: #64748b; font-weight: 600; border-bottom: 2px solid #e2e8f0;">Status</th>
            </tr>
          </thead>
          <tbody>
            ${jobsRowsHtml}
          </tbody>
        </table>
      </div>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
      <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">
        This is an automated alert generated by the Account Health Tracker Dashboard.
      </p>
    </div>
  `;

  try {
    const { error } = await resend.emails.send({
      from: fromEmail,
      to: managementEmail,
      subject,
      html,
    });
    if (error) {
      console.error(`[emailService] Resend API error for ${clientName}:`, error.message);
      return false;
    }
    console.log(`[emailService] Summary email sent for ${clientName} to ${managementEmail}.`);
    return true;
  } catch (err) {
    console.error(`[emailService] Failed to send summary email for ${clientName}:`, err.message);
    return false;
  }
}
