import nodemailer from 'nodemailer';

/**
 * Sends an urgent notification email to management about a pending XL/XXL job.
 * @param {object} params
 * @param {string} params.clientName
 * @param {string} params.jobId
 * @param {string} params.deliverable
 * @param {string} params.priority
 * @param {string} params.dueDate
 * @param {number} params.daysRemaining
 * @returns {Promise<boolean>}
 */
export async function sendAlertEmail({ clientName, jobId, deliverable, priority, dueDate, daysRemaining }) {
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const smtpFrom = process.env.SMTP_FROM || `"Account Health Alerts" <${smtpUser}>`;
  const managementEmail = process.env.MANAGEMENT_EMAIL;

  if (!smtpUser || !smtpPass) {
    console.warn('[emailService] SMTP_USER or SMTP_PASS not set. Skipping email delivery.');
    return false;
  }
  if (!managementEmail) {
    console.warn('[emailService] MANAGEMENT_EMAIL not set. Skipping email delivery.');
    return false;
  }

  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  const subject = `[Urgent Alert] ${priority} Job Due in ${daysRemaining} Days for ${clientName}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #f8fafc;">
      <h2 style="color: #d97706; margin-top: 0; font-size: 20px;">⚠️ High-Priority Job Due Soon</h2>
      <p style="font-size: 15px; color: #334155; line-height: 1.5; margin-bottom: 20px;">
        The following high-priority <strong>${priority}</strong> job is scheduled for delivery in <strong>${daysRemaining} days</strong>.
      </p>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; width: 140px; border-bottom: 1px solid #f1f5f9;">Client:</td>
          <td style="padding: 8px 0; color: #0f172a; font-weight: 500; border-bottom: 1px solid #f1f5f9;">${clientName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Job ID:</td>
          <td style="padding: 8px 0; color: #0f172a; font-family: monospace; font-size: 13px; border-bottom: 1px solid #f1f5f9;">${jobId}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Deliverable:</td>
          <td style="padding: 8px 0; color: #0f172a; font-weight: 500; border-bottom: 1px solid #f1f5f9;">${deliverable}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Priority / Size:</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f1f5f9;">
            <span style="background-color: ${priority === 'XXL' ? '#0d9488' : '#d97706'}; color: white; padding: 3px 10px; border-radius: 6px; font-weight: bold; font-size: 11px; letter-spacing: 0.05em;">
              ${priority}
            </span>
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-weight: bold; border-bottom: 1px solid #f1f5f9;">Due Date:</td>
          <td style="padding: 8px 0; color: #ef4444; font-weight: bold; border-bottom: 1px solid #f1f5f9;">${dueDate}</td>
        </tr>
      </table>
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
      <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">
        This is an automated alert generated by the Account Health Tracker Dashboard.
      </p>
    </div>
  `;

  try {
    const info = await transporter.sendMail({
      from: smtpFrom,
      to: managementEmail,
      subject,
      html,
    });
    console.log(`[emailService] Alert email sent for Job ${jobId} to ${managementEmail}. Message ID: ${info.messageId}`);
    return true;
  } catch (err) {
    console.error(`[emailService] Failed to send alert email for Job ${jobId}:`, err.message);
    return false;
  }
}
